server:
  servlet:
    context-path: /api/rabbitx/v1/
  port: 9006

margin:
  limit: 10
  leverage: 10

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:rabbitxorderbook
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

---
spring:
  config:
    activate:
      on-profile: test
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testrabbit
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true