server:
  servlet:
    context-path: /api/rabbitx/v1/

margin:
  limit: 10

spring:
  datasource:
    url: jdbc:h2:mem:rabbitxorderbook
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

---
spring:
  profiles:
    active: test

margin:
  limit: 1
  leverage: 10
